# aka application.properties

# rsa
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

# server configs
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# springboot configs
spring:
  # our database
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: 1111
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # our ORM
  jpa:
    hibernate:
      # todo: change to not drop all tables on reinit
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # https://stackoverflow.com/questions/47603204/spring-boot-jpa-error-error-executing-ddl-via-jdbc-statement
        globally_quoted_identifiers: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: username
    password: 1111

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000